### ISSUE TITLE
Pre-Lollipop animation is weird

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [balysv/material-menu#27]
When animating from burger to arrow, It looks like it's spinning, and then the burger is fading out and the arrow is fading in.

Is it possible to change this?

**Comment by balysv** [comment]
Could you provide a video or gif to demonstrate?

**Comment by AndroidDeveloperLB** [comment]
Sure.
Just please let me know when to delete the video.
Here it is:
https://drive.google.com/file/d/0B-PZZGk2vPohc3dmdUFNOU1sanM/

**Comment by balysv** [comment]
It looks like you are either reinitialising some part of layout or recreating it completely with `animateLayoutChanges` enabled. It is your layout that does the fading.
The library could not behave that way even if it wanted. It is just a `Drawable` with animated transformations. They behave the same way for every version since it is using the `Canvas` api

**Comment by AndroidDeveloperLB** [comment]
No, I didn't perform any animations on the layout. There is a transition between the activities, but when reaching the second activity I wait till the keyboard is shown, and only then I start the view's animation.
Also, when leaving the second activity, I first perform the animation and then really close the activity.
Not only that, but for Kitkat and below, I've disabled any transitions between activities.

Here's the relevant code:

    mMaterialMenuView = (MaterialMenuView) findViewById(R.id.navButton);
    mMaterialMenuView.setState(IconState.BURGER);
    mMaterialMenuView.setTransformationDuration(1000);
    // the next line is called after the keyboard is shown:
    mMaterialMenuView.animateState(IconState.ARROW);
